# @package _global_
defaults:
  - acdc_image_adapter_280_bz8_ts200.yaml
  - _self_

paths:
  experiment_log_dir: /data/home/shujia/CardioSAM/outputs/acdc_adapter_280_bz8_ts300

scratch:
  scheduler_timescale: 300

trainer:
  logging:
    wandb_writer:
      name: acdc_adapter_280_bz8_ts300
      tags: [acdc, sam3, adapter, res280, ts300]

