# @package _global_
defaults:
  - acdc_image_adapter_280_bz8_ts200.yaml
  - _self_

paths:
  experiment_log_dir: /data/home/shujia/CardioSAM/outputs/acdc_adapter_280_bz8_ts350

scratch:
  scheduler_timescale: 350

trainer:
  logging:
    wandb_writer:
      name: acdc_adapter_280_bz8_ts350
      tags: [acdc, sam3, adapter, res280, ts350]

# TRITON_CACHE_DIR=/data/home/shujia/triton_cache CUDA_VISIBLE_DEVICES=1 \
# python sam3/train/train.py -c configs/acdc/acdc_image_adapter_280_bz8_ts350.yaml --use-cluster 0 --num-gpus 1 \
# 2>&1 | tee /data/home/shujia/CardioSAM/outputs/acdc_adapter_280_bz8_ts350/train.log